version: '3.8'

services:
  # --- TON AJOUT INFRA : LE REVERSE PROXY ---
  proxy:
    image: nginx:alpine
    container_name: parkshare-proxy
    ports:
      - "80:80"  # Le SEUL port ouvert sur Internet !
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - api
    restart: unless-stopped

  # --- LES SERVICES DU DEV (Sécurisés) ---
  db:
    image: postgres:15-alpine
    container_name: parkshare-db
    environment:
      POSTGRES_USER: parkshare_user
      POSTGRES_PASSWORD: parkshare_password
      POSTGRES_DB: parkshare
    # J'AI SUPPRIMÉ LES PORTS ICI POUR LA SÉCURITÉ !
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: 
      context: ../app/api
    container_name: parkshare-api
    # J'AI SUPPRIMÉ LES PORTS ICI AUSSI !
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: 
      context: ../app/frontend
    container_name: parkshare-frontend
    # J'AI SUPPRIMÉ LES PORTS ICI AUSSI (Nginx fait le relais) !
    environment:
      VITE_API_URL: http://localhost/api  # Modifié pour passer par Nginx
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pg-data: