services:
  # --- 1. LE REVERSE PROXY ---
  proxy:
    image: nginx:alpine
    container_name: parkshare-proxy
    ports:
      - "80:80"  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - parkshare_net
    depends_on:
      - frontend
      - api
    restart: unless-stopped

  # --- 2. LA BASE DE DONNÉES ---
  db:
    image: postgres:15-alpine
    container_name: parkshare-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - parkshare_net
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # --- 3. LE BACKEND (API) ---
  api:
    build: 
      context: ../app
    container_name: parkshare-api
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    networks:
      - parkshare_net
    depends_on:
      - db
    volumes:
      - ../data:/data
    restart: unless-stopped

  # --- 4. LE FRONTEND (React) ---
  frontend:
    build: 
      context: ../app/frontend
    container_name: parkshare-frontend
    environment:
      VITE_API_URL: /api
    networks:
      - parkshare_net
    depends_on:
      - api
    restart: unless-stopped

# --- RÉSEAU ET VOLUMES ---
networks:
  parkshare_net:
    driver: bridge

volumes:
  pgdata:
