server {
    listen 80;
    server_name _;

    # 1. Tout le trafic normal va vers l'interface React
    location / {
        proxy_pass http://frontend:5173;
        
        # Nécessaire pour React/Vite
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # 2. Les requêtes de données vont vers l'API
    location /api/ {
        proxy_pass http://api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
